# Generated by Django 4.2.2 on 2023-06-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="contactus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_email", models.EmailField(max_length=100)),
                ("client_name", models.CharField(max_length=100)),
                ("client_message", models.CharField(max_length=500)),
            ],
        ),
    ]
