# Generated by Django 4.0.7 on 2023-06-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='images/')),
                ('designation', models.CharField(max_length=30)),
                ('info', models.TextField(max_length=200)),
                ('facebook', models.URLField(null=True)),
                ('instagram', models.URLField(null=True)),
                ('dropbox', models.URLField(null=True)),
                ('twitter', models.URLField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contactus',
            name='client_message',
            field=models.TextField(max_length=500),
        ),
    ]
