# Generated by Django 4.2.2 on 2023-06-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_team_alter_contactus_client_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="clientsay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("comments", models.TextField(max_length=200)),
                ("img", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
