# Generated by Django 4.2.2 on 2023-06-06 09:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_blog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="blog",
        ),
    ]
